function parseBody(req){if(typeof req.body==='string'){try{return JSON.parse(req.body||'{}')}catch{return {}}}return req.body||{}}
function extractGenerateContentImage(data){const parts=data?.candidates?.[0]?.content?.parts||[];for(const p of parts){const b=p?.inlineData||p?.inline_data;if(b?.data)return {data:b.data,mimeType:b.mimeType||b.mime_type||'image/png'}}return null}
function extractInteractionImage(data){if(data?.output_image?.data)return {data:data.output_image.data,mimeType:data.output_image.mime_type||data.output_image.mimeType||'image/png'};for(const step of data?.steps||[]){if(step?.type!=='model_output')continue;for(const block of step?.content||[]){if(block?.type==='image'&&block?.data)return {data:block.data,mimeType:block.mime_type||block.mime_type||'image/png'};}}return null}
function svgFallback(topic){const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));const title=escape(String(topic||'Study visual').replace(/\s+/g,' ').slice(0,58));const labels=['Key concept','Main process','Important link','Outcome'];const fills=['#6d5dfc','#0ea5e9','#f59e0b','#16a34a'];let cards='';for(let i=0;i<4;i++){const x=60+i*240;cards+=`<g><rect x="${x}" y="220" width="205" height="150" rx="24" fill="#fff" stroke="${fills[i]}" stroke-width="5"/><circle cx="${x+102}" cy="260" r="28" fill="${fills[i]}"/><text x="${x+102}" y="268" fill="#fff" font-size="16" font-family="Arial" font-weight="800" text-anchor="middle">${i+1}</text><text x="${x+102}" y="315" fill="#0f172a" font-size="17" font-family="Arial" font-weight="800" text-anchor="middle">${labels[i]}</text><text x="${x+102}" y="343" fill="#64748b" font-size="12" font-family="Arial" text-anchor="middle">Study keywords</text></g>`;if(i<3)cards+=`<path d="M ${x+205} 295 L ${x+230} 295" stroke="#475569" stroke-width="5" marker-end="url(#a)"/>`;}
return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 576"><defs><linearGradient id="bg" x1="0" x2="1"><stop stop-color="#eef2ff"/><stop offset="1" stop-color="#ecfeff"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="8" stdDeviation="10" flood-opacity=".16"/></filter><marker id="a" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0 0 L10 5 L0 10Z" fill="#475569"/></marker></defs><rect width="1024" height="576" rx="30" fill="url(#bg)"/><g filter="url(#shadow)"><rect x="28" y="28" width="968" height="520" rx="30" fill="#fff"/></g><text x="58" y="78" fill="#6d5dfc" font-family="Arial" font-size="15" font-weight="800">NIMBUS STUDY VISUAL</text><text x="58" y="130" fill="#0f172a" font-family="Arial" font-size="30" font-weight="900">${title}</text><text x="58" y="160" fill="#64748b" font-family="Arial" font-size="13">Professional fallback visual • concise labels • 16:9</text>${cards}<text x="58" y="500" fill="#64748b" font-family="Arial" font-size="12">Use the keywords and visual structure as study help, then rephrase explanations in your own words.</text></svg>`).toString('base64')}
async function callInteractions(apiKey,prompt,aspectRatio,imageSize){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({model:'gemini-3.1-flash-image',input:prompt,response_format:{type:'image',mime_type:'image/png',aspect_ratio:aspectRatio,image_size:imageSize}})});const data=await r.json().catch(()=>({}));return {r,data,image:extractInteractionImage(data)};}
async function callGenerateContent(apiKey,model,prompt,aspectRatio,imageSize){const body={contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['IMAGE'],responseFormat:{image:{aspectRatio:aspectRatio,imageSize:imageSize}}}};const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));return {r,data,image:extractGenerateContentImage(data)};}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({ok:false,message:'Method Not Allowed'});try{const body=parseBody(req);const prompt=String(body.prompt||'').trim();if(!prompt)return res.status(400).json({ok:false,message:'No visual prompt was provided.'});const ratio=['16:9','1:1','4:3','3:4','9:16','21:9','3:2','2:3','4:5','5:4'].includes(String(body.aspectRatio||'16:9'))?String(body.aspectRatio||'16:9'):'16:9';const size=['1K','2K','4K','512'].includes(String(body.imageSize||'2K'))?String(body.imageSize||'2K'):'2K';const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(503).json({ok:false,message:'Image generation is not configured.'});
const enhanced=`Create a professional, realistic, presentation-ready educational visual for this request. Use actual subject imagery or realistic illustrated objects, rich coordinated colors, layered depth, lighting, shadows, polished composition, clear hierarchy, meaningful icons, diagrams/flow arrows only when useful, and short readable labels. Never produce a plain text-only answer, generic empty boxes, or a simple arrow chain. Make it look like a high-quality modern educational poster or professional infographic. Keep facts and labels accurate. Request: ${prompt}`;
try{const out=await callInteractions(apiKey,enhanced,ratio,size);if(out.r.ok&&out.image)return res.status(200).json({ok:true,mimeType:out.image.mimeType,data:out.image.data,model:'gemini-3.1-flash-image',api:'interactions'});console.error('[Nimbus visual interactions]',out.data?.error||out.data);}catch(e){console.error('[Nimbus visual interactions error]',e?.message||e)}
for(const model of ['gemini-3.1-flash-image','gemini-2.5-flash-image']){try{const out=await callGenerateContent(apiKey,model,enhanced,ratio,size);if(out.r.ok&&out.image)return res.status(200).json({ok:true,mimeType:out.image.mimeType,data:out.image.data,model});console.error('[Nimbus visual generateContent]',model,out.data?.error||out.data);}catch(e){console.error('[Nimbus visual generateContent error]',model,e?.message||e)}}
return res.status(200).json({ok:true,fallback:true,mimeType:'image/svg+xml',data:svgFallback(prompt),model:'nimbus-local-fallback',message:'Provider image generation was unavailable; showing a topic-specific visual fallback.'});
}catch(e){console.error('[Nimbus visual handler]',e);return res.status(200).json({ok:true,fallback:true,mimeType:'image/svg+xml',data:svgFallback('Educational visual'),model:'nimbus-local-fallback',message:'Provider image generation was unavailable; showing a topic-specific visual fallback.'});}}
